### ISSUE TITLE
How can I create a Figure in the latest version in FreeCAD

### ISSUE THREAD

**Issue by qingfengxia** [FreeCAD/freecad.plot#10] opened 2020-01-22 16:12 UTC
Hi, I am the Cfd module developer,  I see Plot is not official module, then how can I use it as before?

I can create figure, but it does not show up in FreeCAD screen

```
def _createPlotFigure():
    #Plot is not part of Official module in 0.19,
    try:
        import Plot
        return Plot.figure(FreeCAD.ActiveDocument.Name + "Residuals")
    except ImportError:
        # install it from Addon manager,   then how it can be imported
        import freecad.plot.Plot as Plot
        return Plot.figure(FreeCAD.ActiveDocument.Name + "Residuals")  # not working
```

**Comment by looooo** [comment] 2020-01-26 21:49
the function has no problems with my configuration. What is the error?

**Comment by qingfengxia** [comment] 2020-01-27 10:54
thank you for your help.

the figure windows does not show up in the new tab of FreeCAD,  do I need to run  plot.show()
here is the link to the code, it works with Plot as official module,
https://github.com/qingfengxia/Cfd/blob/master/FoamCaseBuilder/FoamResidualPloter.py

Would you have some suggestion to bring it back to work with the latest

try:
    import FreeCAD
    from PySide import QtCore
    withinFreeCAD = True
    try:
        import Plot
        hasPlotMod = True
    except ImportError:
        # install it from Addon manager
        try:
            import freecad.plot.Plot as Plot
            hasPlotMod = True
        except:
            hasPlotMod = False
except:
    withinFreeCAD = False

    import matplotlib
    matplotlib.use("svg")  # save to file?
    import matplotlib.pyplot as plt
    print("matplotlib backend as it is not within FreeCAD: ", plt.get_backend())  #TkAgg
    import matplotlib.animation as animation

def _createPlotFigure():
    #Plot is not part of Official module in 0.19,
    return Plot.figure(FreeCAD.ActiveDocument.Name + "Residuals")





Qingfeng Xia
Senior Research Software Engineer, Culham Centre of Fusion Energy, UKAEA

https://github.com/qingfengxia
https://www.researchgate.net/profile/Qingfeng_Xia
personal website: https://www.iesensor.com

________________________________

**Comment by looooo** [comment] 2020-01-29 15:39
sry, I can't reproduce your error. Can you share your FreeCAD info and the reported error?

**Comment by qingfengxia** [comment] 2020-09-20 19:22
PPA install freecad-daily  in Sep 2020, tested on Ubuntu 20.04,  Python 3.8

```
>>> import Plot
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'Plot'
>>> from freecad.plot import Plot
>>> Plot.figure("a")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/qxia/.FreeCAD/Mod/Plot/freecad/plot/Plot.py", line 110, in figure
    win = Plot(winTitle)
  File "/home/qxia/.FreeCAD/Mod/Plot/freecad/plot/Plot.py", line 423, in __init__
    self.canvas.setParent(self)
TypeError: arguments did not match any overloaded call:
  setParent(self, QWidget): argument 1 has unexpected type 'Plot'
  setParent(self, QWidget, Union[Qt.WindowFlags, Qt.WindowType]): argument 1 has unexpected type 'Plot'
```

**Comment by looooo** [comment] 2020-09-29 13:00
@qingfengxia I wasn't able to reproduce this error. Anyway I am working on a better integration in this branch:
https://github.com/FreeCAD/freecad.plot/tree/simplified_interface

With this branch it's possible to use the matplotlib api directly:
![Bildschirmfoto von 2020-09-29 14-57-54](https://user-images.githubusercontent.com/5084704/94561561-78b44f80-0264-11eb-9d3c-0480bab993e3.png)

**Comment by qingfengxia** [comment] 2020-10-04 11:43
That is great, I am looking fwd to trying it.

**Comment by looooo** [comment] 2020-10-09 09:19
@qingfengxia I have merged the changes into master. So you should be able to use the traditional matplotlib-api to produce the plots. But the Plot workbench is not yet updated to work with the plots produced in this way.

**Comment by sanguinariojoe** [comment] 2021-06-21 09:05
Can be this issue closed?

**Closed as completed** 2021-08-19 12:38 UTC
